# Please use ABSOLUTE PATH for all file paths
# Sample configuration file for SHAPE-MaP pipeline
samples:
  test: 
    modified:
      R1 : "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/Test_Files/samples/SRR30943151_1.fastq.gz"
      R2 : "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/Test_Files/samples/SRR30943151_2.fastq.gz"
    untreated:
      R1 : "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/Test_Files/samples/SRR30943152_1.fastq.gz"
      R2 : "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/Test_Files/samples/SRR30943152_2.fastq.gz"

# Output directory no "/" at the end
output_dir: "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/output"
container: "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/shapemap.sif"

# Target reference file
target: "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/GSE279192_Hs_DRAIC.fa"

# Script settings
scripts:
  split: "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/split_reference.py"
  compile_report: "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/compile_report.py"

# ShapeMapper2 parameters
denatured: false
overwrite: true
indiv_norm: false

# Primer settings
amplicon: false
certain_primer: false
primers_file: 0
random_primer: true
random_primer_length: 6
max_primer_offset: 10

# ShapeMapper2 parameters (delete to set default values)
min_depth: 1000
max_bg: 0.05
min_qual_to_trim: 20
window_to_trim: 5
min_length_to_trim: 25
min_qual_to_count: 30

# RNAstructure parameters
temperature: 37
maximum: 20
loop: 30

# Report generation settings
report_config:
  generate_html: true
  html_template: "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/SHAPE-MaP_Report.html"
  generate_markdown: true
  markdown_template: "/mnt1/4.NAS2025/zhangam/easyomics_test/report/SHAPE-MaP/SHAPE-MaP_Report.md"
  report_title: "SHAPE-MaP Analysis Report"
  institution: "BIG"
  pi_name: "HYJ"
  project_id: "report-test"
  analysis_date: "2026/04/07"
